# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 27ee970f460ac5660804802f35abd18380ab8aaa4a85550edf6f6d647326df16712823a9dd3f6c66eb139a5272d73d2c8cd84c20f10ac965751b18d722c062f3

test:
  secret_key_base: 8715b85e8602ce72eb6d27419d82cf8ec7ea52bebfd1a23c025178b47942ff975571f15555867bde68a8dd9eb7b12e7665b90be5a5b418fd3f7c6fd1d4c88546

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
